package com.example.woods.amin.Database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "IMAGES".
 */
@Entity
public class Images {

    @Id(autoincrement = true)
    private Long id;
    private String uri;
    private Boolean primary;
    private Boolean enable;
    private long product_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Images() {
    }

    public Images(Long id) {
        this.id = id;
    }

    @Generated
    public Images(Long id, String uri, Boolean primary, Boolean enable, long product_id) {
        this.id = id;
        this.uri = uri;
        this.primary = primary;
        this.enable = enable;
        this.product_id = product_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public Boolean getPrimary() {
        return primary;
    }

    public void setPrimary(Boolean primary) {
        this.primary = primary;
    }

    public Boolean getEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(long product_id) {
        this.product_id = product_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
